name: PrisonGangs
main: com.mydeblob.prisongangs.PrisonGangs
version: 2.3
author: mydeblob
commands:
   kdr:
      description: Shows you the KDR of yourself, or a specified player
      usage: /<command> or /<command> playerName
      permission: gangs.kdr
   gang:
      description: Base command for gangs
      usage: /<command> help
      aliases: [g]
   pgupdate:
      description: Updates the plugin
      usage: /<command>
